name: Build Fishpig Theme Composer Package
description: Compiles the Fishpig wordpress theme from source, and generates a composer manifest
author: "SamJUK"

inputs:
  tag:
    description: Tagged version to build
    required: true

outputs:
  hash:
    description: 'Hash of the built package'

runs:
  using: docker
  image: 'Dockerfile'
  args:
    - ${{ inputs.tag }}